#!/usr/bin/env bash
echo ""
echo " Akonado Scripts (macOS)"
echo " ======================="
echo ""
echo " Setup:"
echo "   scripts/macOS/setup.sh           Install Python dependencies"
echo "   scripts/macOS/config.sh          Open .env config for editing"
echo "   scripts/macOS/check.sh           Check provider availability"
echo ""
echo " AI Pipeline:"
echo "   scripts/macOS/skill.sh list      List available LLM skills"
echo "   scripts/macOS/skill.sh run ...   Run an LLM skill"
echo "   scripts/macOS/generate.sh        Generate all assets"
echo "   scripts/macOS/generate.sh TYPE   Generate specific asset type"
echo "   scripts/macOS/pipeline.sh \"X\"    Full pipeline: premise -> all assets"
echo "   scripts/macOS/list.sh            List all manifests"
echo "   scripts/macOS/clean.sh TYPE      Delete generated files"
echo ""
echo " Godot:"
echo "   scripts/macOS/godot.sh           Open Godot editor"
echo "   scripts/macOS/run.sh             Run game in Godot"
echo ""
echo " Web GUI:"
echo "   scripts/macOS/web.sh             Launch browser GUI"
echo ""
echo " Generate types: characters, backgrounds, bgm, se, voice, ui, dialogue, all"
echo " Clean types:    characters, backgrounds, bgm, se, voice, ui, dialogue"
echo ""
